server:
  port: 5000

spring:
  main:
    log-startup-info: false
  datasource:
    url: jdbc:mysql://localhost:3306/jju_assistant?useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: jj39gesge.